# Generated by Django 4.2.5 on 2023-10-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MAIDA BREAD", "MAIDA BREAD"),
                            ("AATA BREAD", "AATA BREAD"),
                            ("BROWN BREAD", "BROWN BREAD"),
                            ("TUTI FRUITY", "TUTI FRUITY"),
                            ("GARLIC BREAD", "GARLIC BREAD"),
                        ],
                        default="AATA BREAD",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("wHITE", "WHITE"),
                            ("BROWN", "BROWN"),
                            ("YELLOW", "YELLOW"),
                        ],
                        default="WHITE",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[
                            (10, "10g"),
                            (15, "15g"),
                            (20, "20g"),
                            (25, "25g"),
                            (30, "30g"),
                            (40, "40g"),
                            (50, "50g"),
                            (100, "100g"),
                        ]
                    ),
                ),
                (
                    "prize",
                    models.IntegerField(
                        choices=[
                            (15, "Rs 15"),
                            (25, "Rs 25"),
                            (40, "Rs 40"),
                            (50, "Rs 50"),
                        ]
                    ),
                ),
            ],
        ),
    ]
